# Generated by Django 4.2.2 on 2023-07-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('trending', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('thumb', models.ImageField(upload_to='blog_images/')),
                ('author_name', models.CharField(default='Author Name', max_length=50)),
                ('author_image', models.ImageField(upload_to='blog_images/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
