# Generated by Django 4.2.3 on 2023-07-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='Author Name', max_length=50),
        ),
    ]
