# Generated by Django 4.2.3 on 2023-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_author_image_article_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_image',
            field=models.ImageField(upload_to='blog_images/'),
        ),
    ]
