# Generated by Django 4.2.3 on 2023-07-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_options_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
