# Generated by Django 4.2.2 on 2023-07-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBase', '0002_user_first_name_user_last_name_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
    ]
