# Generated by Django 4.2.2 on 2023-07-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBase', '0005_user_password2_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(default=False, max_length=254),
        ),
    ]
