name: Deploy to GAE
# Controls when the workflow will run
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    ##### CREATE RUNTIME ENV FILE FOR DEPLOYMENT, AND ADD SERVICE-ACCOUNT-KEY.json IF NEEDED
    - name: Creating Runtime .env and add service-account-key
      run: |
        touch .env
        echo DB_NAME="${{ secrets.DB_NAME }}" >> .env
        echo DB_USER="${{ secrets.DB_USER }}" >> .env
        echo DB_PWD="${{ secrets.DB_PWD }}" >> .env
        echo DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" >> .env
        echo DB_PORT="${{ secrets.DB_PORT }}" >> .env
        echo DB_HOST="${{ secrets.DB_HOST }}" >> .env
    - name: Setup python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Requirements
      run: pip install -r requirements.txt 
    - name: Connect to gcloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT}}
        export_default_credentials: true
    - name: Gather Static Files
      run: python manage.py collectstatic --noinput    ### CREATE RUNTIME MIGRATIONS, THIS MAY CAUSE SOME ERRORS IF MIGRATIONS FOLDER IS NOT MAINTAINED, REMOVE MIGRATIONS FOLDER NAME FROM .gitignore
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.PROJECT_ID }}
        credentials: ${{ secrets.SERVICE_ACCOUNT }}